title: "New Idea"
labels: ["Ideas Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        Precise descriptions of your ideas enable us to thoroughly evaluate their potential and efficiently prioritise for their successful implementation.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: "A clear and concise description of what the feature is and the value it would add to exec.ninja."
      placeholder: |
        I'd like to suggest X to add to the exec.ninja. It will have following benefits:
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: "Explain the problem you're facing without this feature. How does this affect your workflow or use of exec.ninja?"
      placeholder: |
        Without this suggestion, people have to do X to achieve Y which is causing problem Z.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        _Remember to search for duplicates before posting a new feature request. If an identical or similar request already exists, consider commenting there to show your support!_
