title: "New Idea"
labels: ["Ideas Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: "A clear and concise description of what the feature is and the value it would add to exec.ninja."
      placeholder: |
        I'd like to suggest X to add to the exec.ninja. It will have following benefits:
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: "Explain the problem you're facing without this feature. How does this affect your workflow or use of exec.ninja?"
      placeholder: |
        Without this suggestion, people have to do X to achieve Y which is causing problem Z.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        _Remember to search for duplicates before posting a new feature request. If an identical or similar request already exists, consider commenting there to show your support!_
